# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d02e499b4b549ac97609632dca4f234e49a690e65a82206d25621787c778276e3e573c9d63fd2b6d6ac014be8830aefeb47ff839138852e330cf66d3fa2c88ae

test:
  secret_key_base: a6610710c8eccd9bd4f5037e0c6340e68f71ec0a67552091cf1bbdda5af003f6aeeb8af85b3377fc2acb6a32a609858cda1be7ffaef354ae1cc541970245db20

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
